### ISSUE TITLE
Storage Test: History: Test undoLastCommand(string&, Item&, vector<Item>&);

### ISSUE THREAD

**Issue by andysohwz** [cs2103jan2015-f10-2c/main#138]

**Comment by leejoonfai** [comment]
Andy, there seems to be a problem with undoLastCommand when it tries to undo an Edit command. Refer to the unit test pushed at 4 Apr 21:33. Problem occurs at line 1935 in the test. Refer to the error message thrown by the test and the StackTrace. Seems like problem is with the use of square brackets to access members of _schedule (?)
![untitled](https://cloud.githubusercontent.com/assets/10784575/6992842/dea31d1e-db12-11e4-88de-23d1e2c1ee00.png)

**Comment by leejoonfai** [comment]
undoing Adds and Deletes are fine, only problem is with undoing Edit

**Comment by leejoonfai** [comment]
SORRY MY BAD. PROBLEM ON MY END!! Test passed! issue closed!

**Comment by andysohwz** [comment]
Thanks! I was trying to look through my code as well! :D
